name: Windows tests

on:
  push

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        image: [
          "datadog/agent-dev:vboulineau-fix-windows-py3-jmx-win",
          "datadog/agent-dev:paulcacheux-upgrade-opa-rego-py3-jmx-win",
          "datadog/agent-dev:paulcacheux-upgrade-opa-rego-fail-py3-jmx-win"
        ]

    steps:
      - name: Pull image
        run: |
          docker pull ${{ matrix.image }}
      - name: Run container
        run: |
          $job = Start-Job -ScriptBlock {
            docker run --rm -e DD_API_KEY='api_key_test' ${{ matrix.image }}
          }
          $job | Wait-Job -Timeout 30
          $job | Receive-Job
