name: Windows tests

on:
  push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Run container
        run: |
          docker pull datadog/agent-dev:vboulineau-fix-windows-py3-jmx-win
          $job = Start-Job -ScriptBlock {
            docker run --rm -e DD_API_KEY='api_key_test' datadog/agent-dev:vboulineau-fix-windows-py3-jmx-win
          }
          $job | Wait-Job -Timeout 30
